<##################################################################################################

    Description
    ===========

	- This script does the following - 
		- installs chocolatey
		- installs specified chocolatey packages

	- This script generates logs in the following folder - 
		- %ALLUSERSPROFILE%\ChocolateyPackageInstaller-{TimeStamp}\Logs folder.


    Usage examples
    ==============
    
    Powershell -executionpolicy bypass -file ChocolateyPackageInstaller.ps1


    Pre-Requisites
    ==============

    - Ensure that the powershell execution policy is set to unrestricted (@TODO).


    Known issues / Caveats
    ======================
    
    - No known issues.


    Coming soon / planned work
    ==========================

    - N/A.    

##################################################################################################>

#
# Optional arguments to this script file.
#

Param(
    # comma or semicolon separated list of chocolatey packages.
    [ValidateNotNullOrEmpty()]
    [string]
    $RawPackagesList
)

##################################################################################################

#
# Powershell Configurations
#

# Note: Because the $ErrorActionPreference is "Stop", this script will stop on first failure.  
# $ErrorActionPreference = "stop"
$ErrorActionPreference = 'SilentlyContinue'

# Ensure that current process can run scripts. 
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force 

###################################################################################################

#
# Custom Configurations
#

$ChocolateyPackageInstallerFolder = Join-Path $env:ALLUSERSPROFILE -ChildPath $("ChocolateyPackageInstaller-" + [System.DateTime]::Now.ToString("yyyy-MM-dd-HH-mm-ss"))

# Location of the log files
$ScriptLog = Join-Path -Path $ChocolateyPackageInstallerFolder -ChildPath "ChocolateyPackageInstaller.log"
$ChocolateyInstallLog = Join-Path -Path $ChocolateyPackageInstallerFolder -ChildPath "ChocolateyInstall.log"

##################################################################################################

# 
# Description:
#  - Displays the script argument values (default or user-supplied).
#
# Parameters:
#  - N/A.
#
# Return:
#  - N/A.
#
# Notes:
#  - Please ensure that the Initialize() method has been called at least once before this 
#    method. Else this method can only write to console and not to log files. 
#

function DisplayArgValues
{
    WriteLog "========== Configuration =========="
    WriteLog $("RawPackagesList : " + $RawPackagesList)
    WriteLog "========== Configuration =========="
}

##################################################################################################

# 
# Description:
#  - Creates the folder structure which'll be used for dumping logs generated by this script and
#    the logon task.
#
# Parameters:
#  - N/A.
#
# Return:
#  - N/A.
#
# Notes:
#  - N/A.
#

function InitializeFolders
{
    if ($false -eq (Test-Path -Path $ChocolateyPackageInstallerFolder))
    {
        New-Item -Path $ChocolateyPackageInstallerFolder -ItemType directory | Out-Null
    }
}

##################################################################################################

# 
# Description:
#  - Writes specified string to the console as well as to the script log (indicated by $ScriptLog).
#
# Parameters:
#  - $message: The string to write.
#
# Return:
#  - N/A.
#
# Notes:
#  - N/A.
#

function WriteLog
{
    Param(
        <# Can be null or empty #> $message
    )

    $timestampedMessage = $("[" + [System.DateTime]::Now + "] " + $message) | % {  
        Write-Host -Object $_
        Out-File -InputObject $_ -FilePath $ScriptLog -Append
    }
}

##################################################################################################

# 
# Description:
#  - Installs the chocolatey package manager.
#
# Parameters:
#  - N/A.
#
# Return:
#  - If installation is successful, then nothing is returned.
#  - Else a detailed terminating error is thrown.
#
# Notes:
#  - @TODO: Write to $chocolateyInstallLog log file.
#  - @TODO: Currently no errors are being written to the log file ($chocolateyInstallLog). This needs to be fixed.
#

function InstallChocolatey
{
    Param(
        [ValidateNotNullOrEmpty()] $chocolateyInstallLog
    )

    WriteLog "Installing Chocolatey..."

    Invoke-Expression ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')) | Out-Null

    WriteLog "Success."
}

##################################################################################################

#
# Description:
#  - Installs the specified chocolatet packages on the machine.
#
# Parameters:
#  - N/A.
#
# Return:
#  - N/A.
#
# Notes:
#  - N/A.
#

function InstallPackages
{
    Param(
        [ValidateNotNullOrEmpty()][string] $packagesList
    )

    $Separator = @(";",",")
    $SplitOption = [System.StringSplitOptions]::RemoveEmptyEntries
    $packages = $packagesList.Trim().Split($Separator, $SplitOption)

    if (0 -eq $packages.Count)
    {
        WriteLog $("No packages were specified. Exiting...")
        return        
    }

    foreach ($package in $packages)
    {
        WriteLog $("Installing package: " + $package)

        # install git via chocolatey
        choco install $package --force --yes --acceptlicense --verbose | Out-Null 

        if ($? -eq $false)
        {
            $errMsg = $("Error! Installation failed. Please see the chocolatey logs in %ALLUSERSPROFILE%\chocolatey\logs folder for details.")
            WriteLog $errMsg
            Write-Error $errMsg 
        }
    
        WriteLog "Success."        
    }
}

##################################################################################################

#
# Description:
#  - Download Windows 2012 r2 ISO on the machine.
#
# Parameters:
#  - N/A.
#
# Return:
#  - N/A.
#
# Notes:
#  - N/A.
#

function DownloadWindows2012r2
{

    WriteLog $("Started-DownloadWindows2012r2")
    $output = "c:\win2012r2.iso"
    if ((Test-Path $output)) {
        WriteLog $("ISO already exists")
        throw "$output already exists"
    }

    # Update SourcePath
    $url = "http://care.dlservice.microsoft.com/dl/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO"
    WriteLog $("Downloading:" + $output)
    (New-Object System.Net.WebClient).DownloadFile($url, $output)

    WriteLog $("Mounting ISO:" + $output)

    if (Test-Path $output) { 
        if((Get-Item $output).length -gt 0kb){
            WriteLog $("File exists and not 0kb:")
        }
    }

    if ( -not (Test-Path $output)) {
        WriteLog $("File does not exist:" + $output)
        throw "$output does not exist"
    }

    # while (!(Test-Path $output)) { Start-Sleep 10 }
    Mount-DiskImage -ImagePath $output -ErrorAction SilentlyContinue
    WriteLog $("Ready to Import")
    $driveLetter = (get-diskimage -imagepath $output|Get-Volume).DriveLetter
    WriteLog $("Driveletter to Import:" + $driveletter)
}

##################################################################################################

#
# Description:
#  - Configure MDT on the machine.
#
# Parameters:
#  - N/A.
#
# Return:
#  - N/A.
#
# Notes:
#  - N/A.
#

function ConfigureMDT
{

    WriteLog $("Started-ConfigureMDT")
    $output = "c:\win2012r2.iso"

    # Update SourcePath
    $url = "http://care.dlservice.microsoft.com/dl/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO"
    WriteLog $("Downloading:" + $output)
    (New-Object System.Net.WebClient).DownloadFile($url, $output)

    # Setup-DeploymentShare
    WriteLog $("Setting up MDT Share")
    New-Item -Path "C:\DeploymentShare" -ItemType directory -ErrorAction SilentlyContinue
    New-SmbShare -Name "DeploymentShare$" -Path "C:\DeploymentShare" -FullAccess Administrators -ErrorAction SilentlyContinue
    Import-Module "C:\Program Files\Microsoft Deployment Toolkit\bin\MicrosoftDeploymentToolkit.psd1"

    # Update NetworkPath if server name not MDTServer
    new-PSDrive -Name "DS001" -PSProvider "MDTProvider" -Root "C:\DeploymentShare" -Description "MDT Deployment Share" -NetworkPath ("\\" + $env:computername + "\DeploymentShare$") -Verbose | add-MDTPersistentDrive -Verbose -ErrorAction SilentlyContinue

    # Update Packages example below for WMF 5.0
    WriteLog $("Setting up Packages")
    new-item -path "DS001:\Packages" -enable "True" -Name "Win2012r2" -Comments "" -ItemType "folder" -Verbose -ErrorAction SilentlyContinue
    New-Item -Path "C:\DeploymentShare\PackageSource" -ItemType directory -ErrorAction SilentlyContinue
    Invoke-WebRequest -Uri 'http://go.microsoft.com/fwlink/?LinkId=717507' -OutFile 'C:\DeploymentShare\PackageSource\Win8.1AndW2K12R2-KB3134758-x64.msu'
    import-mdtpackage -path "DS001:\Packages\Win2012r2" -SourcePath "C:\DeploymentShare\PackageSource" -Verbose

    # Setup MDT Applications
    WriteLog $("Setting up Applications")
    Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cliveg/dtlartifacts/master/mdt/EnableRDP.ps1' -OutFile 'C:\DeploymentShare\Applications\EnableRDP.ps1'
    new-item -path "DS001:\Applications" -enable "True" -Name "Tweaks" -Comments "" -ItemType "folder" -Verbose -ErrorAction SilentlyContinue
    import-MDTApplication -path "DS001:\Applications\Tweaks" -enable "True" -Name "Microsoft Enable Remote Desktop" -ShortName "Enable Remote Desktop" -Version "" -Publisher "Microsoft" -Language "" -CommandLine "Powershell -noprofile -executionpolicy bypass -file .\EnableRDP.ps1" -WorkingDirectory ".\Applications" -NoSource -Verbose

    # Update CustomerSettings.ini and Bootstrap.ini
    WriteLog $("Setting up CustomSettings")
    Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cliveg/dtlartifacts/master/mdt/CustomSettings.ini' -OutFile 'C:\DeploymentShare\Control\CustomSettings.ini'
    Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cliveg/dtlartifacts/master/mdt/Bootstrap.ini' -OutFile 'C:\DeploymentShare\Control\Bootstrap.ini'
    Add-Content C:\DeploymentShare\Control\Bootstrap.ini ("`nDeployRoot=\\" + $env:computername + "\DeploymentShare$")
    New-Item -Path "C:\DeploymentShare\SLShare" -ItemType directory -ErrorAction SilentlyContinue
    Add-Content C:\DeploymentShare\Control\CustomSettings.ini ("`nSLShare=\\" + $env:computername + "\DeploymentShare$\SLShare")
    Add-Content C:\DeploymentShare\Control\CustomSettings.ini ("`nEventService=http://" + $env:computername + ":9800")

    WriteLog $("Setting up ConfigMgr Tools")
    Invoke-WebRequest -Uri 'https://download.microsoft.com/download/5/0/8/508918E1-3627-4383-B7D8-AA07B3490D21/ConfigMgrTools.msi' -OutFile 'C:\DeploymentShare\ConfigMgrTools.msi'
    #Start-Process 'C:\DeploymentShare\ConfigMgrTools.msi' /qn -Wait

    $driveLetter = (get-diskimage -imagepath $output|Get-Volume).DriveLetter

    import-mdtoperatingsystem -path "DS001:\Operating Systems" -SourcePath ($driveLetter + ":\") -DestinationFolder "win2012r2" -Verbose
    WriteLog $("Imported")
    DisMount-DiskImage -ImagePath $output -ErrorAction SilentlyContinue
    WriteLog $("Dismounted")
    #Remove-Item $output
    WriteLog $("Importing Complete - " + (Test-Path 'c:\deploymentshare\Operating Systems\win2012r2'))

    # Create Task Sequence
    import-mdttasksequence -path "DS001:\Task Sequences" -Name "Windows Server 2012 R2 Standard" -Template "Server.xml" -Comments "" -ID "Server2012r2std" -Version "1.0" -OperatingSystemPath "DS001:\Operating Systems\Windows Server 2012 R2 SERVERSTANDARD in win2012r2 install.wim" -FullName "Employee" -OrgName "Microsoft Corporation" -HomePage "about:blank" -AdminPassword "P@ssword1" -Verbose
    Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cliveg/dtlartifacts/master/mdt/ts.xml' -OutFile 'C:\DeploymentShare\Control\SERVER2012R2STD\ts.xml'

    # Update Deployment Share
    WriteLog $("Updating Deployment Share")
    update-MDTDeploymentShare -path "DS001:" -Verbose
    WriteLog $("Updating Deployment Share - Complete")

    # Build Image
    Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cliveg/dtlartifacts/master/mdt/diskpart1.txt' -OutFile 'C:\DeploymentShare\diskpart1.txt'
    Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cliveg/dtlartifacts/master/mdt/diskpart2.txt' -OutFile 'C:\DeploymentShare\diskpart2.txt'
    Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cliveg/dtlartifacts/master/mdt/CreateVHD.cmd' -OutFile 'C:\DeploymentShare\CreateVHD.cmd'

    # C:\Windows\system32\cmd.exe /k
    # CD "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\"
    # CD "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment"
    # C:\DeploymentShare\CreateVHD.cmd
    WriteLog $("Calling CreateVHD")
    $out = C:\DeploymentShare\CreateVHD.cmd
    WriteLog $("CreateVHD " + $out)
}

##################################################################################################



#
# 
#

try
{
    #
    InitializeFolders

    #
    DisplayArgValues

    #
    DownloadWindows2012r2
    
    # install the chocolatey package manager
    InstallChocolatey -chocolateyInstallLog $ChocolateyInstallLog

    # install the specified packages
    InstallPackages -packagesList $RawPackagesList

    # configure MDT
    ConfigureMDT


}
catch
{
    if (($null -ne $Error[0]) -and ($null -ne $Error[0].Exception) -and ($null -ne $Error[0].Exception.Message))
    {
        $errMsg = $Error[0].Exception.Message
        WriteLog $errMsg
        Write-Host $errMsg
    }

    # Important note: Throwing a terminating error (using $ErrorActionPreference = "stop") still returns exit 
    # code zero from the powershell script. The workaround is to use try/catch blocks and return a non-zero 
    # exit code from the catch block. 
    exit -1
}